server:
  port: 8084

spring:
  application:
    name: ai-service
  profiles:
    active: dev

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/readup_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # MyBatis Plus配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: auto
        logic-delete-field: deleted
        logic-delete-value: 1
        logic-not-delete-value: 0
        table-prefix: t_
    mapper-locations: classpath*:mapper/**/*.xml

# Spring AI配置 - 使用DeepSeek API
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-e005be5ef3b0410da65d30969e33fa67
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
          max-tokens: 2000

# 日志配置
logging:
  level:
    com.xreadup.ai: debug
    com.baomidou.mybatisplus: info
    org.springframework.cloud: info
    org.springframework.ai: debug

