server:
  port: 8081
#  servlet:
#    context-path: /api

spring:
  application:
    name: user-service
  
#  # 禁用Spring Cloud兼容性检查
#  cloud:
#    compatibility-verifier:
#      enabled: false
    nacos:
      discovery:
              server-addr: localhost:8848
              namespace: public
              group: DEFAULT_GROUP
              # 健康检查
              heart-beat-interval: 5000
              heart-beat-timeout: 15000
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/readup_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms




mybatis-plus:
  # 全局配置
  global-config:
    db-config:
      # 主键策略
      id-type: auto
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 表名前缀
      table-prefix: t_
  
  # 配置
  configuration:
    # 驼峰命名转换
    map-underscore-to-camel-case: true
    # SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 缓存配置
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: simple
  
  # 扫描路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.xreadup.userservice.model.entity

jwt:
  secret: readupSecretKey2025ForJWTAuthenticationWithStrongSecurity
  expiration: 86400000  # 24小时 (单位: 毫秒)
  refresh-expiration: 604800000  # 7天刷新有效期
  token-prefix: Bearer
  header-string: Authorization

logging:
  level:
    com.xreadup.userservice: debug
    com.baomidou.mybatisplus: info
    org.springframework.cloud: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-service.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    enable-version: true
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always